# Generated by Django 3.1.3 on 2020-12-01 02:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('capacitor_type', models.CharField(choices=[('Ceramic capacitor', 'ceramic'), ('Electrolytic capacitor', 'electrolytic'), ('Air capacitor', 'air'), ('Film capacitor', 'film'), ('Mica capacitor', 'mica'), ('Polymer capacitor', 'polymer'), ('Supercapacitor', 'super'), ('Tantalum capacitor', 'tantalum')], default='ceramic', max_length=255)),
                ('polarized', models.BooleanField(default=False)),
                ('capacitance', models.FloatField(blank=True, default=0)),
                ('max_voltage', models.FloatField(blank=True, default=0)),
                ('max_temperature', models.FloatField(blank=True, default=0)),
                ('tolerance', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Diode',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('voltage_drop', models.FloatField(default=0)),
                ('breakdown_voltage', models.FloatField(blank=True, default=0)),
                ('diode_type', models.CharField(choices=[('rectifier', 'rectifier'), ('schottky', 'schottky'), ('zener', 'zener'), ('led', 'led'), ('photo diode', 'photodiode'), ('laser diode', 'laserdiode'), ('tunnel diode', 'tunneldiode'), ('backward diode', 'backwarddiode'), ('avalanche diode', 'avalanchediode'), ('TVS diode', 'tvsdioide'), ('constant current diode', 'constantcurrentdiode'), ('vacuum diode', 'vacuumdiode'), ('step recovery diode', 'steprecoverydiode')], default='rectifier', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Fuse',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('rated_current', models.FloatField(default=0)),
                ('trigger_characteristics', models.CharField(choices=[('superflink', 'FF'), ('flink', 'F'), ('mittelträge', 'M'), ('träge', 'T'), ('superträge', 'TT')], default='F', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Inductor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('inductance', models.FloatField(default=0)),
                ('core_material', models.CharField(choices=[('air', 'air'), ('iron', 'iron'), ('ferrite', 'ferrite')], default='air', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='MagnetoResistor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('max_power_dissipation', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='PhotoResistor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('max_power_dissipation', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Potentiometer',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('max_power_dissipation', models.FloatField(blank=True, default=0)),
                ('min_resistance', models.FloatField(default=0)),
                ('max_resistance', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('max_current', models.FloatField(default=0)),
                ('max_voltage', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Resistor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('max_power_dissipation', models.FloatField(blank=True, default=0)),
                ('resistance', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='ShuntResistor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('max_power_dissipation', models.FloatField(blank=True, default=0)),
                ('max_current', models.FloatField(default=0)),
                ('temperature_coefficient', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Thermistor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('max_power_dissipation', models.FloatField(blank=True, default=0)),
                ('thermistor_type', models.CharField(choices=[('NTC', 'NTC'), ('PTC', 'PTC')], default='NTC', max_length=255)),
                ('temp_min', models.FloatField(blank=True, default=0)),
                ('temp_max', models.FloatField(blank=True, default=0)),
                ('temp_switch', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('max_voltage_primary', models.FloatField(default=0)),
                ('max_power_dissipation', models.FloatField(default=0)),
                ('transform_ratio', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='TrimmerCapacitor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('polarized', models.BooleanField(default=False)),
                ('max_voltage', models.FloatField(blank=True, default=0)),
                ('max_temperature', models.FloatField(blank=True, default=0)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('min_capacitance', models.FloatField(blank=True, default=0)),
                ('max_capacitance', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='UniqueItem',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('name', models.CharField(default='', max_length=255)),
            ],
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='VariableInductor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('min_inductance', models.FloatField(default=0)),
                ('max_inductance', models.FloatField(default=0)),
                ('core_material', models.CharField(choices=[('air', 'air'), ('iron', 'iron'), ('ferrite', 'ferrite')], default='air', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Varistor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('tolerance', models.FloatField(blank=True, default=0)),
                ('max_power_dissipation', models.FloatField(blank=True, default=0)),
                ('breakdown_voltage', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.abstractitem')),
                ('schematic_symbol_path', models.CharField(blank=True, default='', max_length=1024)),
                ('datasheet_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mounting', models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255)),
                ('length', models.FloatField(default=0)),
                ('diameter', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.abstractitem',),
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('_base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.abstractitem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.container')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='_custom_values',
            field=models.ManyToManyField(blank=True, to='backend.KeyValuePair'),
        ),
    ]
