# Generated by Django 3.1.3 on 2020-11-26 07:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.containermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.containermodel')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resistor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schematic_symbol_path', models.CharField(default='', max_length=1024)),
                ('datasheet_path', models.CharField(default='', max_length=1024)),
                ('resistance', models.FloatField(default=0)),
                ('tolerance', models.FloatField(default=0)),
                ('custom_values', models.ManyToManyField(to='backend.KeyValuePair')),
                ('locations', models.ManyToManyField(to='backend.ItemLocationModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('custom_values', models.ManyToManyField(to='backend.KeyValuePair')),
                ('locations', models.ManyToManyField(to='backend.ItemLocationModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
