# Generated by Django 3.1.3 on 2020-12-01 01:29

from django.db import migrations


def create_roots(apps, schema_editor):
    Container = apps.get_model("backend", "Container")
    root, new = Container.objects.get_or_create(id=0, name="", parent_id=0)
    if new:
        root.save()

    Category = apps.get_model("backend", "Category")
    root, new = Category.objects.get_or_create(id=0, name="", parent_id=0)
    if new:
        root.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roots)
    ]
