# Generated by Django 3.1.3 on 2020-11-26 06:52

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemlocationmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='locations',
            field=models.ManyToManyField(to='backend.ItemLocationModel'),
        ),
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dictionary')),
            ],
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='custom_values',
            field=models.ForeignKey(default=backend.models._create_default_dict, on_delete=django.db.models.deletion.CASCADE, to='backend.dictionary'),
        ),
    ]
