# Generated by Django 3.1.3 on 2020-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resistor',
            name='max_power_dissipation',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resistor',
            name='mounting',
            field=models.CharField(choices=[('THT', 'THT'), ('SMD', 'SMD'), ('Other', 'Other')], default='THT', max_length=255),
        ),
        migrations.AlterField(
            model_name='resistor',
            name='datasheet_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='resistor',
            name='schematic_symbol_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='resistor',
            name='tolerance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
