# Generated by Django 4.0 on 2021-12-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0002_create_roots'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stringvalue')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='stringvariable',
            name='key',
        ),
        migrations.RemoveField(
            model_name='stringvariable',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stringvariable',
            name='value',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children_manager', to='backend.category'),
        ),
        migrations.AlterField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children_manager', to='backend.container'),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children_manager', to='backend.itemtemplate'),
        ),
        migrations.DeleteModel(
            name='FloatVariable',
        ),
        migrations.DeleteModel(
            name='StringVariable',
        ),
    ]
