# Generated by Django 3.1.3 on 2020-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201126_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='custom_values',
            field=models.ManyToManyField(blank=True, to='backend.KeyValuePair'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='locations',
            field=models.ManyToManyField(blank=True, to='backend.ItemLocationModel'),
        ),
        migrations.AlterField(
            model_name='resistor',
            name='custom_values',
            field=models.ManyToManyField(blank=True, to='backend.KeyValuePair'),
        ),
        migrations.AlterField(
            model_name='resistor',
            name='locations',
            field=models.ManyToManyField(blank=True, to='backend.ItemLocationModel'),
        ),
    ]
