# Generated by Django 3.2.3 on 2021-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_create_roots'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fields',
            field=models.ManyToManyField(to='backend.StringValue'),
        ),
    ]
