# Generated by Django 4.0 on 2021-12-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_keyvaluepair_remove_stringvariable_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyvaluepair',
            old_name='value',
            new_name='value_id',
        ),
        migrations.AlterField(
            model_name='keyvaluepair',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_for_kvp', to='backend.stringvalue'),
        ),
    ]
