# Generated by Django 4.0 on 2021-12-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_value_keyvaluepair_value_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvaluepair',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_in_pairs', to='backend.stringvalue'),
        ),
        migrations.CreateModel(
            name='UnitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.IntegerField(choices=[(-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'), (-12, 'p'), (-9, 'n'), (-6, 'u'), (-3, 'm'), (-2, 'c'), (-1, 'd'), (24, 'Y'), (21, 'Z'), (18, 'E'), (15, 'P'), (12, 'T'), (9, 'G'), (6, 'M'), (3, 'k'), (2, 'h'), (1, 'D')])),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.floatvalue')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stringvalue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
