# Generated by Django 3.2.3 on 2021-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integervariable',
            name='key',
        ),
        migrations.RemoveField(
            model_name='integervariable',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='integervariable',
            name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='name_template',
            field=models.CharField(blank='', default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='IntegerValue',
        ),
        migrations.DeleteModel(
            name='IntegerVariable',
        ),
    ]
