# Generated by Django 4.0 on 2021-12-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_keyvaluepair_key_unitvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitvalue',
            old_name='prefix',
            new_name='expo',
        ),
    ]
