# Generated by Django 4.0 on 2021-12-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_prefix_unitvalue_expo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitvalue',
            name='expo',
        ),
    ]
