# Generated by Django 3.1.3 on 2020-11-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_relay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContainerModel',
            new_name='Container',
        ),
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='ItemLocationModel',
            new_name='ItemLocation',
        ),
    ]
