# Generated by Django 3.1.3 on 2020-11-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_capacitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitor',
            name='capacitance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
