# Generated by Django 3.1.3 on 2020-12-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201130_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.container'),
        ),
    ]
