# Generated by Django 3.1.3 on 2020-12-01 01:29

from django.db import migrations


def create_root(apps, schema_editor):
    Container = apps.get_model("backend", "Container")
    root, new = Container.objects.get_or_create(id=0, name="", parent_id=0)
    if new:
        root.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20201201_0134'),
    ]

    operations = [
        migrations.RunPython(create_root)
    ]
